// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolAppTracker.Data;

#nullable disable

namespace SchoolAppTracker.Migrations
{
    [DbContext(typeof(SchoolAppTrackerContext))]
    [Migration("20260217021300_AddRosterPopulations")]
    partial class AddRosterPopulations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("school")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchoolAppTracker.Data.Data.Application", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal?>("AnnualCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ContractEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ContractStartDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("CoppaCompliant")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataPrivacyAgreementUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FerpaCompliant")
                        .HasColumnType("bit");

                    b.Property<string>("LicenseType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumberOfLicenses")
                        .HasColumnType("int");

                    b.Property<bool>("RosterGuardians")
                        .HasColumnType("bit");

                    b.Property<bool>("RosterStudents")
                        .HasColumnType("bit");

                    b.Property<bool>("RosterTeachers")
                        .HasColumnType("bit");

                    b.Property<int>("RosteringMethod")
                        .HasColumnType("int");

                    b.Property<bool>("SsoEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("SsoProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("VendorContact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CategoryId");

                    b.ToTable("Applications", "school");
                });

            modelBuilder.Entity("SchoolAppTracker.Data.Data.ApplicationDepartment", b =>
                {
                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.HasKey("ApplicationId", "DepartmentId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("ApplicationDepartments", "school");
                });

            modelBuilder.Entity("SchoolAppTracker.Data.Data.ApplicationGradeLevel", b =>
                {
                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<int>("GradeLevelId")
                        .HasColumnType("int");

                    b.HasKey("ApplicationId", "GradeLevelId");

                    b.HasIndex("GradeLevelId");

                    b.ToTable("ApplicationGradeLevels", "school");
                });

            modelBuilder.Entity("SchoolAppTracker.Data.Data.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Categories", "school");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Learning Management"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Assessment"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Communication"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Productivity"
                        },
                        new
                        {
                            ID = 5,
                            Name = "Administrative"
                        },
                        new
                        {
                            ID = 6,
                            Name = "Special Education"
                        });
                });

            modelBuilder.Entity("SchoolAppTracker.Data.Data.Department", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Departments", "school");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Math"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Science"
                        },
                        new
                        {
                            ID = 3,
                            Name = "English"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Social Studies"
                        },
                        new
                        {
                            ID = 5,
                            Name = "IT"
                        },
                        new
                        {
                            ID = 6,
                            Name = "Administration"
                        },
                        new
                        {
                            ID = 7,
                            Name = "Counseling"
                        },
                        new
                        {
                            ID = 8,
                            Name = "Special Education"
                        });
                });

            modelBuilder.Entity("SchoolAppTracker.Data.Data.GradeLevel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("GradeLevels", "school");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "K"
                        },
                        new
                        {
                            ID = 2,
                            Name = "1"
                        },
                        new
                        {
                            ID = 3,
                            Name = "2"
                        },
                        new
                        {
                            ID = 4,
                            Name = "3"
                        },
                        new
                        {
                            ID = 5,
                            Name = "4"
                        },
                        new
                        {
                            ID = 6,
                            Name = "5"
                        },
                        new
                        {
                            ID = 7,
                            Name = "6"
                        },
                        new
                        {
                            ID = 8,
                            Name = "7"
                        },
                        new
                        {
                            ID = 9,
                            Name = "8"
                        },
                        new
                        {
                            ID = 10,
                            Name = "9"
                        },
                        new
                        {
                            ID = 11,
                            Name = "10"
                        },
                        new
                        {
                            ID = 12,
                            Name = "11"
                        },
                        new
                        {
                            ID = 13,
                            Name = "12"
                        });
                });

            modelBuilder.Entity("SchoolAppTracker.Data.Data.Screenshot", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("ApplicationId");

                    b.ToTable("Screenshots", "school");
                });

            modelBuilder.Entity("SchoolAppTracker.Data.Data.Application", b =>
                {
                    b.HasOne("SchoolAppTracker.Data.Data.Category", "Category")
                        .WithMany("Applications")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SchoolAppTracker.Data.Data.ApplicationDepartment", b =>
                {
                    b.HasOne("SchoolAppTracker.Data.Data.Application", "Application")
                        .WithMany("ApplicationDepartments")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SchoolAppTracker.Data.Data.Department", "Department")
                        .WithMany("ApplicationDepartments")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("SchoolAppTracker.Data.Data.ApplicationGradeLevel", b =>
                {
                    b.HasOne("SchoolAppTracker.Data.Data.Application", "Application")
                        .WithMany("ApplicationGradeLevels")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SchoolAppTracker.Data.Data.GradeLevel", "GradeLevel")
                        .WithMany("ApplicationGradeLevels")
                        .HasForeignKey("GradeLevelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("GradeLevel");
                });

            modelBuilder.Entity("SchoolAppTracker.Data.Data.Screenshot", b =>
                {
                    b.HasOne("SchoolAppTracker.Data.Data.Application", "Application")
                        .WithMany("Screenshots")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("SchoolAppTracker.Data.Data.Application", b =>
                {
                    b.Navigation("ApplicationDepartments");

                    b.Navigation("ApplicationGradeLevels");

                    b.Navigation("Screenshots");
                });

            modelBuilder.Entity("SchoolAppTracker.Data.Data.Category", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("SchoolAppTracker.Data.Data.Department", b =>
                {
                    b.Navigation("ApplicationDepartments");
                });

            modelBuilder.Entity("SchoolAppTracker.Data.Data.GradeLevel", b =>
                {
                    b.Navigation("ApplicationGradeLevels");
                });
#pragma warning restore 612, 618
        }
    }
}
